services:

  db:
    build: ./database
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      mynetwork:
        ipv4_address: 172.25.192.20


  backend:
    build: ./backend
    container_name: backend-api
    restart: always

    depends_on:
      - db

    environment:
      DB_HOST: 172.25.192.20
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "8000:8000"

    networks:
      mynetwork:
        ipv4_address: 172.25.192.21


volumes:
  pgdata:


networks:
  mynetwork:
    external: true